  frontend: {
    data: [
      {
        logo: "/assets/frontend/1.png",
        title: "HTML5",
        desc: "HTML5 is a markup language used for structuring and presenting content on the World Wide Web.",
        question: "Do you have knowledge about HTML5?",
        answer: null,
      },
      {
        logo: "/assets/frontend/2.png",
        title: "CSS3",
        desc: "CSS is designed to enable the separation of presentation and content, including layout, colors, and fonts",
        question: "Do you have knowledge about CSS3?",
        answer: null,
      },
      {
        logo: "/assets/frontend/3.png",
        title: "Bootstrap",
        desc: "Bootstrap utilizes Sass for a modular and customizable architecture. ",
        question: "Do you have knowledge about Bootstrap?",
        answer: null,
      },
      {
        logo: "/assets/frontend/4.png",
        title: "Javascript       ",
        desc: "JavaScript (JS) is a lightweight, interpreted, or just-in-time compiled programming language with first-class functions. ",
        question: "Do you have knowledge about javascript?",
        answer: null,
      },
      {
        logo: "/assets/frontend/5.png",
        title: "jQuery",
        desc: "jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation",
        question: "Do you have knowledge about jQuery?",
        answer: null,
      },
      {
        logo: "/assets/frontend/6.png",
        title: "ES6",
        desc: "JavaScript ES6 is the newer version of JavaScript that was introduced in 2015. ",
        question: "Do you have knowledge about ES6?",
        answer: null,
      },
      {
        logo: "/assets/frontend/7.png",
        title: "npm Script",
        desc: "An npm script is a convenient way to bundle common shell commands for your project.",
        question: "Do you have knowledge about npm script?",
        answer: null,
      },
      {
        logo: "/assets/frontend/8.png",
        title: "TypeScript",
        desc: "TypeScript is a strongly typed programming language that builds on JavaScript, giving you better tooling at any scale. k",
        question: "Do you have knowledge about Typescript?",
        answer: null,
      },
      {
        logo: "/assets/frontend/9.png",
        title: "React.js",
        desc: "React is a JavaScript library developed by Facebook which, among other things, was used to build Instagram.com.",
        question: "Do you have knowledge about React.js?",
        answer: null,
      },
      {
        logo: "/assets/frontend/10.png",
        title: "Angular.js",
        desc: "AngularJS extends HTML with new attributes. AngularJS is perfect for Single Page Applications (SPAs).",
        question: "Do you have knowledge about Angular.js?",
        answer: null,
      },
      {
        logo: "/assets/frontend/11.png",
        title: "Vue.js",
        desc: "Vue.js is an open-source front end JavaScript framework for building user interfaces and single-page applications.",
        question: "Do you have knowledge about Vue.js?",
        answer: null,
      },
    ],
    progressLabel: "frontend development",
    endSkillTitle: "frontend development skill",
  }
 